name: clinical_nli
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - attrs=21.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - cymem=2.0.5
  - cython-blis=0.7.4
  - ffmpeg=4.3
  - freetype=2.10.4
  - gettext=0.21.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - idna=2.10
  - intel-openmp=2021.2.0
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.0.2
  - lame=3.100
  - lcms2=2.12
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libidn2=2.3.1
  - libpng=1.6.37
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - murmurhash=1.0.5
  - ncurses=6.2
  - nettle=3.7.2
  - ninja=1.10.2
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1k
  - pandas=1.2.4
  - pillow=8.2.0
  - pip=21.1.1
  - plac=1.1.0
  - preshed=3.0.5
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.5
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytorch=1.8.1
  - pytz=2021.1
  - readline=8.1
  - requests=2.25.1
  - scikit-learn=0.24.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tqdm=4.59.0
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - urllib3=1.26.4
  - wasabi=0.8.2
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - catalogue==2.0.4
    - click==7.1.2
    - conllu==4.4
    - cycler==0.10.0
    - en-core-sci-lg==0.4.0
    - en-core-sci-sm==0.4.0
    - fasttext==0.9.2
    - filelock==3.0.12
    - huggingface-hub==0.0.8
    - jinja2==3.0.1
    - jsonlines==2.0.0
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - nmslib==2.1.1
    - packaging==20.9
    - pathy==0.5.2
    - psutil==5.8.0
    - pybind11==2.6.1
    - pydantic==1.7.4
    - pyparsing==2.4.7
    - pysbd==0.3.4
    - regex==2021.4.4
    - sacremoses==0.0.45
    - scipy==1.6.3
    - scispacy==0.4.0
    - seaborn==0.11.1
    - smart-open==3.0.0
    - spacy==3.0.6
    - spacy-legacy==3.0.5
    - srsly==2.4.1
    - thinc==8.0.3
    - tokenizers==0.10.3
    - transformers==4.6.1
    - typer==0.3.2
